name: all-lints

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "src/oscsim/run.py src/oscsim/modules/arguments.py src/oscsim/modules/helper.py src/oscsim/modules/ngsi.py src/oscsim/modules/output.py src/oscsim/modules/sensor_things.py"
          use-mypy: false

